# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Run marp-action setup
        id: marp-action
        uses: aheil/marp-action@v1.0.0
        with:
          src-dir: 'slides'